#!/usr/bin/env bash

name=`uname -s`
hardware=`uname -m`

binary=${0%.multi}.$name\_$hardware

if [ ! -f $binary ]; then
	(
	echo "songidx.multi: no binary found for $name $hardware"
	printf "    available platforms: "
	ls ${0%.multi}.* | cut -c 11- | tr "\n" " "
	) >&2
	exit 1
fi

echo exec $binary $@
exec $binary $@